/**
 * Constantes de Limites - RPO V5
 */

const LIMITS = {
  POSTGRES_IDENTIFIER_MAX_LENGTH: 63,
  VARCHAR_SHORT: 100,
  VARCHAR_MEDIUM: 255,
  VARCHAR_LONG: 500,
  POOL_MAX_CONNECTIONS: 50,
  POOL_MIN_CONNECTIONS: 2,
  MAX_BATCH_INSERT: 1000,
  MAX_ARRAY_SIZE: 10000,
  MAX_CACHE_AGE_SECONDS: 300,
  MAX_MEMORY_CACHE_SIZE: 1000
};

const DEFAULTS = {
  PORT_API: 7000,
  PORT_VALKEY: 6379,
  PORT_POSTGRES: 15432,
  HOST_LOCALHOST: 'localhost',
  SCHEMA_DEFAULT: 'RPO_template_v5',
  ALTERADO_POR_DEFAULT: 'sistema',
  VERSION_INITIAL: 1,
  VALKEY_PREFIX: 'RPO_V5'
};

module.exports = {
  LIMITS,
  DEFAULTS
};
